<a href="https://colab.research.google.com/github/Chinki021/pandas/blob/main/2)DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

creating dataframes

In [3]:
data={
    'Name':['Chinki','Gullu','Lillu','Pillu'],
    'Age':[30,45,98,3],
    'City':['Scotland','Laddak','Mumbai','Kolkata'],
    'Salary':[80000000000,9100000000,8500,34567]
}
df=pd.DataFrame(data)
df

     Name  Age      City       Salary
0  Chinki   30  Scotland  80000000000
1   Gullu   45    Laddak   9100000000
2   Lillu   98    Mumbai         8500
3   Pillu    3   Kolkata        34567

In [6]:
data_list=[
    ['John',28,'New York',8976],
    ['Anna',45,'Gaya',90282984],
    ['Peter',29,'Berlin',9000],
    ['Puchii',32,'Gaya',100000]
]
df2=pd.DataFrame(data_list)
df2

        0   1         2         3
0    John  28  New York      8976
1    Anna  45      Gaya  90282984
2   Peter  29    Berlin      9000
3  Puchii  32      Gaya    100000

In [9]:
data_list=[
    ['John',28,'New York',8976],
    ['Anna',45,'Gaya',90282984],
    ['Peter',29,'Berlin',9000],
    ['Puchii',32,'Gaya',100000]
]
columns=['Name','Age','City','Salary']
df3=pd.DataFrame(data_list,columns=columns)
df3

     Name  Age      City    Salary
0    John   28  New York      8976
1    Anna   45      Gaya  90282984
2   Peter   29    Berlin      9000
3  Puchii   32      Gaya    100000

Selection and Indexing of columns

In [13]:
df3['Name']

0      John
1      Anna
2     Peter
3    Puchii
Name: Name, dtype: object

In [14]:
df3[['Name','City']]

     Name      City
0    John  New York
1    Anna      Gaya
2   Peter    Berlin
3  Puchii      Gaya

Creating new columns

In [15]:
df3['Designation']=['Doctor','Engineer','Doctor','Engineer']
df3

     Name  Age      City    Salary Designation
0    John   28  New York      8976      Doctor
1    Anna   45      Gaya  90282984    Engineer
2   Peter   29    Berlin      9000      Doctor
3  Puchii   32      Gaya    100000    Engineer

Removing columns

In [16]:
df3.drop('Designation',axis=1)

     Name  Age      City    Salary
0    John   28  New York      8976
1    Anna   45      Gaya  90282984
2   Peter   29    Berlin      9000
3  Puchii   32      Gaya    100000

In [17]:
df3

     Name  Age      City    Salary Designation
0    John   28  New York      8976      Doctor
1    Anna   45      Gaya  90282984    Engineer
2   Peter   29    Berlin      9000      Doctor
3  Puchii   32      Gaya    100000    Engineer

In [18]:
#delecting permamentaly using inplace
df3.drop('Designation',axis=1,inplace=True)
df3

     Name  Age      City    Salary
0    John   28  New York      8976
1    Anna   45      Gaya  90282984
2   Peter   29    Berlin      9000
3  Puchii   32      Gaya    100000

In [19]:
df3

     Name  Age      City    Salary
0    John   28  New York      8976
1    Anna   45      Gaya  90282984
2   Peter   29    Berlin      9000
3  Puchii   32      Gaya    100000

In [21]:
#delecting multiple columns
df3.drop(['Salary','City'], axis=1)

     Name  Age
0    John   28
1    Anna   45
2   Peter   29
3  Puchii   32

In [22]:
df3.drop(0,axis=0)

     Name  Age    City    Salary
1    Anna   45    Gaya  90282984
2   Peter   29  Berlin      9000
3  Puchii   32    Gaya    100000

In [23]:
#selection rows

df3.loc[0]

Name          John
Age             28
City      New York
Salary        8976
Name: 0, dtype: object

In [25]:
df3.loc[[0,1]]

   Name  Age      City    Salary
0  John   28  New York      8976
1  Anna   45      Gaya  90282984

selecting subsets of rows and columns

In [27]:
df3.loc[[0,1]][['City','Salary']]

       City    Salary
0  New York      8976
1      Gaya  90282984

conditional selection

In [28]:
#i only want to see those ppl whose age is >30
df3[df3['Age']>30]

     Name  Age  City    Salary
1    Anna   45  Gaya  90282984
3  Puchii   32  Gaya    100000

In [35]:
#i only want to see those ppl whose  age is >30 and salary is >100000
df3[(df3['Age']>30) & (df3['Salary']>100000)]

   Name  Age  City    Salary
1  Anna   45  Gaya  90282984