<a href="https://colab.research.google.com/github/Chinki021/pandas/blob/main/4)MergingJoiningConcatination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

merging 2 dataframes

In [2]:
employees=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['seema','reema','santanu','pradeep','timku'],
    'department':['HR','IT','Finance','IT','HR']
})

Salaries=pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[60000,70000,50000,90000,10000],
    'bonus':[5000,1000,60000,40000,5000]
})

In [3]:
pd.merge(employees,Salaries)

   employee_id     name department  salary  bonus
0            1    seema         HR   60000   5000
1            2    reema         IT   70000   1000
2            3  santanu    Finance   50000  60000

In [4]:
pd.merge(employees,Salaries,on='employee_id')

   employee_id     name department  salary  bonus
0            1    seema         HR   60000   5000
1            2    reema         IT   70000   1000
2            3  santanu    Finance   50000  60000

In [5]:
pd.merge(employees,Salaries,on='employee_id',how='inner')

   employee_id     name department  salary  bonus
0            1    seema         HR   60000   5000
1            2    reema         IT   70000   1000
2            3  santanu    Finance   50000  60000

In [6]:
pd.merge(employees,Salaries,on='employee_id',how='outer')

   employee_id     name department   salary    bonus
0            1    seema         HR  60000.0   5000.0
1            2    reema         IT  70000.0   1000.0
2            3  santanu    Finance  50000.0  60000.0
3            4  pradeep         IT      NaN      NaN
4            5    timku         HR      NaN      NaN
5            6      NaN        NaN  90000.0  40000.0
6            7      NaN        NaN  10000.0   5000.0

In [7]:
pd.merge(employees,Salaries,on='employee_id',how='left')

   employee_id     name department   salary    bonus
0            1    seema         HR  60000.0   5000.0
1            2    reema         IT  70000.0   1000.0
2            3  santanu    Finance  50000.0  60000.0
3            4  pradeep         IT      NaN      NaN
4            5    timku         HR      NaN      NaN

In [8]:
pd.merge(employees,Salaries,on='employee_id',how='right')

   employee_id     name department  salary  bonus
0            1    seema         HR   60000   5000
1            2    reema         IT   70000   1000
2            3  santanu    Finance   50000  60000
3            6      NaN        NaN   90000  40000
4            7      NaN        NaN   10000   5000

concatination of 2 dataframes

In [10]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [11]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [12]:
pd.concat([df1,df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

joining 2 data frames

In [13]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])


df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [14]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [15]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [16]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN